import type { MovieSelect } from "@/db/schema";

export const MOVIES: MovieSelect[] = [
  {
    id: "mov_001",
    tmdbId: 550,
    title: "Fight Club",
    originalTitle: "Fight Club",
    overview:
      "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vyYX8TX6ySnO8WSp7.jpg",
    releaseDate: "1999-10-15",
    runtime: 139,
    voteAverage: 8.4,
    genres: '["Drama", "Thriller", "Comedy"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_001/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_001/sub_en.vtt",
    torrentHash: "7B1A3D1E2F4A9B6C8D0E1F3A5B7C9D1E3F5A7B9C",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1709964000000),
    currentTime: 3450.5,
    duration: 8340.0,
    watchedAt: new Date(1710050400000),
  },
  {
    id: "mov_002",
    tmdbId: 157336,
    title: "Interstellar",
    originalTitle: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to reach the far reaches of our universe.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/gEU2QlsUUHXjNpeVDHjZ2xKk61D.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/xJHwXaH5Q5zBv5j2I0Dq1q92qWz.jpg",
    releaseDate: "2014-11-05",
    runtime: 169,
    voteAverage: 8.6,
    genres: '["Adventure", "Drama", "Science Fiction"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: "1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B",
    downloadState: "downloading",
    downloadProgress: 0.452,
    downloadSpeed: 2500000,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_003",
    tmdbId: 155,
    title: "The Dark Knight",
    originalTitle: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    releaseDate: "2008-07-16",
    runtime: 152,
    voteAverage: 8.5,
    genres: '["Drama", "Action", "Crime", "Thriller"]',
    isBookmarked: true,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: null,
    downloadState: "idle",
    downloadProgress: 0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_004",
    tmdbId: 693134,
    title: "Dune: Part Two",
    originalTitle: "Dune: Part Two",
    overview:
      "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2TGbi443v.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/8rpDcsfLJypbO6vtec0oUuIv5v4.jpg",
    releaseDate: "2024-02-27",
    runtime: 166,
    voteAverage: 8.3,
    genres: '["Science Fiction", "Adventure"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_004/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_004/sub_en.vtt",
    torrentHash: "2A3B4C5D6E7F8A9B0C1D2E3F4A5B6C7D8E9F0A1B",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1710150000000),
    currentTime: 9960.0,
    duration: 9960.0,
    watchedAt: new Date(1710200000000),
  },
  {
    id: "mov_005",
    tmdbId: 118340,
    title: "Guardians of the Galaxy",
    originalTitle: "Guardians of the Galaxy",
    overview:
      "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after stealing an orb coveted by Ronan.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/r7jJhlo3kGCApE1A0iW3h1eS6i2.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/uLtVbjvS1O7gXL8lUOwsFOH4ma0.jpg",
    releaseDate: "2014-07-30",
    runtime: 121,
    voteAverage: 7.9,
    genres: '["Action", "Science Fiction", "Adventure"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: "3A4B5C6D7E8F9A0B1C2D3E4F5A6B7C8D9E0F1A2B",
    downloadState: "queued",
    downloadProgress: 0.0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_006",
    tmdbId: 27205,
    title: "Inception",
    originalTitle: "Inception",
    overview:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/s3TBrRGB1inv7qiqi4nAc5xQkFs.jpg",
    releaseDate: "2010-07-15",
    runtime: 148,
    voteAverage: 8.4,
    genres: '["Action", "Science Fiction", "Adventure"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_006/video.mp4",
    localSubtitlePath: null,
    torrentHash: "4A5B6C7D8E9F0A1B2C3D4E5F6A7B8C9D0E1F2A3B",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1708000000000),
    currentTime: 120.5,
    duration: 8880.0,
    watchedAt: new Date(1708500000000),
  },
  {
    id: "mov_007",
    tmdbId: 13,
    title: "Forrest Gump",
    originalTitle: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events — in each case, far exceeding what anyone imagined he could do.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    releaseDate: "1994-06-23",
    runtime: 142,
    voteAverage: 8.5,
    genres: '["Comedy", "Drama", "Romance"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: null,
    downloadState: "idle",
    downloadProgress: 0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_008",
    tmdbId: 324857,
    title: "Spider-Man: Into the Spider-Verse",
    originalTitle: "Spider-Man: Into the Spider-Verse",
    overview:
      "Miles Morales is juggling his life between being a high school student and being Spider-Man. However, when Wilson Kingpin Fisk uses a super collider, another Spider-Man is transported to his dimension.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg",
    releaseDate: "2018-12-06",
    runtime: 117,
    voteAverage: 8.4,
    genres: '["Action", "Adventure", "Animation", "Science Fiction"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_008/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_008/sub_en.vtt",
    torrentHash: "5A6B7C8D9E0F1A2B3C4D5E6F7A8B9C0D1E2F3A4B",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1710100000000),
    currentTime: 3500.0,
    duration: 7020.0,
    watchedAt: new Date(1710120000000),
  },
  {
    id: "mov_009",
    tmdbId: 769,
    title: "Goodfellas",
    originalTitle: "Goodfellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a New York crime family.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/sw7mordbZxgITU877yTpZCud90M.jpg",
    releaseDate: "1990-09-12",
    runtime: 145,
    voteAverage: 8.5,
    genres: '["Drama", "Crime"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: "6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2E3F4A5B",
    downloadState: "downloading",
    downloadProgress: 0.895,
    downloadSpeed: 5600000,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_010",
    tmdbId: 238,
    title: "The Godfather",
    originalTitle: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When patriarch Vito Corleone barely survives an assassination attempt, his youngest son Michael steps in to take care of the would-be killers.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    releaseDate: "1972-03-14",
    runtime: 175,
    voteAverage: 8.7,
    genres: '["Drama", "Crime"]',
    isBookmarked: true,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: null,
    downloadState: "idle",
    downloadProgress: 0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_011",
    tmdbId: 122,
    title: "The Lord of the Rings: The Return of the King",
    originalTitle: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/lXhgNSYcqGZMTdUvCqljaLNTfL7.jpg",
    releaseDate: "2003-12-01",
    runtime: 201,
    voteAverage: 8.5,
    genres: '["Adventure", "Fantasy", "Action"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_011/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_011/sub_en.vtt",
    torrentHash: "7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1710155000000),
    currentTime: 0,
    duration: 12060.0,
    watchedAt: null,
  },
  {
    id: "mov_012",
    tmdbId: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    originalTitle: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn's full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    releaseDate: "2023-05-31",
    runtime: 140,
    voteAverage: 8.4,
    genres: '["Action", "Adventure", "Animation", "Science Fiction"]',
    isBookmarked: false,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_012/video.mp4",
    localSubtitlePath: null,
    torrentHash: "8A9B0C1D2E3F4A5B6C7D8E9F0A1B2C3D4E5F6A7B",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1705000000000),
    currentTime: 8400.0,
    duration: 8400.0,
    watchedAt: new Date(1705008400000),
  },
  {
    id: "mov_013",
    tmdbId: 313369,
    title: "La La Land",
    originalTitle: "La La Land",
    overview:
      "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars. But when Mia and Sebastian's fates intertwine in a surprising turn of events, making their dreams a reality means losing each other.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rl0.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/qJeU7KM4nT2C1WpOrwPcSDGFUWE.jpg",
    releaseDate: "2016-11-29",
    runtime: 128,
    voteAverage: 7.9,
    genres: '["Comedy", "Drama", "Romance"]',
    isBookmarked: true,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: "9A0B1C2D3E4F5A6B7C8D9E0F1A2B3C4D5E6F7A8B",
    downloadState: "downloading",
    downloadProgress: 0.123,
    downloadSpeed: 1200000,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_014",
    tmdbId: 11,
    title: "Star Wars",
    originalTitle: "Star Wars",
    overview:
      "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg",
    releaseDate: "1977-05-25",
    runtime: 121,
    voteAverage: 8.2,
    genres: '["Adventure", "Action", "Science Fiction"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: null,
    downloadState: "idle",
    downloadProgress: 0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_015",
    tmdbId: 372058,
    title: "Your Name.",
    originalTitle: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha becomes Taki for a day, and Taki becomes Mitsuha.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    releaseDate: "2016-08-26",
    runtime: 106,
    voteAverage: 8.5,
    genres: '["Romance", "Animation", "Drama"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_015/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_015/sub_en.vtt",
    torrentHash: "0A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1710160000000),
    currentTime: 500.0,
    duration: 6360.0,
    watchedAt: new Date(1710165000000),
  },
  {
    id: "mov_016",
    tmdbId: 424,
    title: "Schindler's List",
    originalTitle: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    releaseDate: "1993-12-15",
    runtime: 195,
    voteAverage: 8.6,
    genres: '["Drama", "History", "War"]',
    isBookmarked: true,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: "1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C",
    downloadState: "queued",
    downloadProgress: 0.0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_017",
    tmdbId: 496243,
    title: "Parasite",
    originalTitle: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes a peculiar interest in the wealthy and glamorous Park family and starts to infiltrate their household by posing as unrelated, highly qualified individuals.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    releaseDate: "2019-05-30",
    runtime: 133,
    voteAverage: 8.5,
    genres: '["Comedy", "Thriller", "Drama"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_017/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_017/sub_en.vtt",
    torrentHash: "2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1709000000000),
    currentTime: 7980.0,
    duration: 7980.0,
    watchedAt: new Date(1709100000000),
  },
  {
    id: "mov_018",
    tmdbId: 129,
    title: "Spirited Away",
    originalTitle: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkBg8lWOb.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/bSXfU4dwZyBA1vMmXvejdRXB2Fk.jpg",
    releaseDate: "2001-07-20",
    runtime: 125,
    voteAverage: 8.5,
    genres: '["Animation", "Family", "Fantasy"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: null,
    downloadState: "idle",
    downloadProgress: 0,
    downloadSpeed: 0,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
  {
    id: "mov_019",
    tmdbId: 671,
    title: "Harry Potter and the Philosopher's Stone",
    originalTitle: "Harry Potter and the Philosopher's Stone",
    overview:
      "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/wuMc08JTpWXvH1yU543YtoXp9W3.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
    releaseDate: "2001-11-16",
    runtime: 152,
    voteAverage: 7.9,
    genres: '["Adventure", "Fantasy"]',
    isBookmarked: true,
    isOffline: true,
    localVideoPath: "file:///data/user/0/com.cue/files/mov_019/video.mp4",
    localSubtitlePath: "file:///data/user/0/com.cue/files/mov_019/sub_en.vtt",
    torrentHash: "3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2E",
    downloadState: "complete",
    downloadProgress: 1.0,
    downloadSpeed: 0,
    downloadedAt: new Date(1710180000000),
    currentTime: 4500.0,
    duration: 9120.0,
    watchedAt: new Date(1710185000000),
  },
  {
    id: "mov_020",
    tmdbId: 808,
    title: "Shrek",
    originalTitle: "Shrek",
    overview:
      "It ain't easy bein' green — especially if you're a likable (albeit smelly) ogre named Shrek. On a mission to retrieve a princess from a fire-breathing dragon, Shrek teams up with an unlikely compatriot — a wisecracking donkey.",
    posterPath:
      "https://image.tmdb.org/t/p/w500/iB64vpL3dIObYclAl18320OmsAQ.jpg",
    backdropPath:
      "https://image.tmdb.org/t/p/w1280/5aRnsHk5q5i6EaWdEqpT6UvX4K3.jpg",
    releaseDate: "2001-05-18",
    runtime: 90,
    voteAverage: 7.7,
    genres: '["Animation", "Comedy", "Family", "Fantasy"]',
    isBookmarked: false,
    isOffline: false,
    localVideoPath: null,
    localSubtitlePath: null,
    torrentHash: "4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2E3F",
    downloadState: "downloading",
    downloadProgress: 0.781,
    downloadSpeed: 4100000,
    downloadedAt: null,
    currentTime: 0,
    duration: 0,
    watchedAt: null,
  },
];
